-- Current Barlas Print Studio schema. Dedicated project only.
create schema if not exists private;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,phone text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists private.admins(user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz not null default now());
create or replace function private.is_current_user_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from private.admins a where a.user_id=(select auth.uid()));$$;
revoke all on function private.is_current_user_admin() from public;grant usage on schema private to authenticated;grant execute on function private.is_current_user_admin() to authenticated;
create or replace function public.is_current_user_admin() returns boolean language sql stable security invoker set search_path='' as $$select private.is_current_user_admin();$$;
revoke all on function public.is_current_user_admin() from public;grant execute on function public.is_current_user_admin() to authenticated;
create or replace function private.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,full_name) values(new.id,nullif(new.raw_user_meta_data->>'full_name','')) on conflict(id) do nothing;return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure private.handle_new_user();
create table if not exists public.quote_requests(id bigint generated by default as identity primary key,user_id uuid references auth.users(id) on delete set null,full_name text not null,email text not null,phone text,product text not null check(product in('flyer','brochure','card','apparel','mug','poster','stickers','banner','vinyl','window_graphics','one_way_vision','frosted_film','signage','stationery','design','website')),quantity integer not null check(quantity>0 and quantity<=1000000),size text,paper text,print_sides text not null default 'single' check(print_sides in('single','double')),finish text not null default 'standard',design_service boolean not null default false,notes text,estimated_total numeric(12,2),status text not null default 'new' check(status in('new','reviewing','quoted','approved','declined','converted')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.quote_files(id bigint generated by default as identity primary key,quote_id bigint not null references public.quote_requests(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,storage_path text not null unique,original_name text not null,created_at timestamptz not null default now());
create sequence if not exists public.order_number_seq;
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_number text not null unique,user_id uuid not null references auth.users(id) on delete restrict,quote_id bigint references public.quote_requests(id) on delete set null,status text not null default 'approved' check(status in('approved','processing','printing','quality_check','ready','shipped','completed','cancelled')),subtotal numeric(12,2) not null default 0,gst numeric(12,2) not null default 0,total numeric(12,2) not null default 0,delivery_method text,due_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create or replace function private.set_order_number() returns trigger language plpgsql set search_path='' as $$begin if new.order_number is null or btrim(new.order_number)='' then new.order_number:='BPS-'||to_char(current_date,'YYYY')||'-'||lpad(nextval('public.order_number_seq')::text,4,'0');end if;return new;end;$$;
drop trigger if exists before_order_number on public.orders;create trigger before_order_number before insert on public.orders for each row execute procedure private.set_order_number();
create table if not exists public.order_items(id bigint generated by default as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,product text not null,description text,quantity integer not null check(quantity>0),unit_price numeric(12,2) not null default 0,line_total numeric(12,2) not null default 0,created_at timestamptz not null default now());
alter table public.profiles enable row level security;alter table public.quote_requests enable row level security;alter table public.quote_files enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;
revoke all on public.profiles from anon,authenticated;revoke all on public.quote_requests from anon,authenticated;revoke all on public.quote_files from anon,authenticated;revoke all on public.orders from anon,authenticated;revoke all on public.order_items from anon,authenticated;
grant select,update on public.profiles to authenticated;grant insert on public.quote_requests to anon;grant insert,select,update on public.quote_requests to authenticated;grant insert,select on public.quote_files to authenticated;grant select,insert,update,delete on public.orders to authenticated;grant select,insert,update,delete on public.order_items to authenticated;
grant usage,select on sequence public.quote_requests_id_seq to anon,authenticated;grant usage,select on sequence public.quote_files_id_seq to authenticated;grant usage,select on sequence public.order_items_id_seq to authenticated;grant usage,select on sequence public.order_number_seq to authenticated;
create policy "profiles_select_self_or_admin" on public.profiles for select to authenticated using((select auth.uid())=id or (select private.is_current_user_admin()));
create policy "profiles_update_self_or_admin" on public.profiles for update to authenticated using((select auth.uid())=id or (select private.is_current_user_admin())) with check((select auth.uid())=id or (select private.is_current_user_admin()));
create policy "quotes_anon_insert" on public.quote_requests for insert to anon with check(user_id is null);
create policy "quotes_authenticated_insert" on public.quote_requests for insert to authenticated with check(user_id=(select auth.uid()));
create policy "quotes_select_owner_or_admin" on public.quote_requests for select to authenticated using(user_id=(select auth.uid()) or (select private.is_current_user_admin()));
create policy "quotes_admin_update" on public.quote_requests for update to authenticated using((select private.is_current_user_admin())) with check((select private.is_current_user_admin()));
create policy "quote_files_insert_owner" on public.quote_files for insert to authenticated with check(user_id=(select auth.uid()));
create policy "quote_files_select_owner_or_admin" on public.quote_files for select to authenticated using(user_id=(select auth.uid()) or (select private.is_current_user_admin()));
create policy "orders_select_owner_or_admin" on public.orders for select to authenticated using(user_id=(select auth.uid()) or (select private.is_current_user_admin()));
create policy "orders_admin_insert" on public.orders for insert to authenticated with check((select private.is_current_user_admin()));
create policy "orders_admin_update" on public.orders for update to authenticated using((select private.is_current_user_admin())) with check((select private.is_current_user_admin()));
create policy "orders_admin_delete" on public.orders for delete to authenticated using((select private.is_current_user_admin()));
create policy "order_items_select_owner_or_admin" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and(o.user_id=(select auth.uid()) or(select private.is_current_user_admin()))));
create policy "order_items_admin_insert" on public.order_items for insert to authenticated with check((select private.is_current_user_admin()));
create policy "order_items_admin_update" on public.order_items for update to authenticated using((select private.is_current_user_admin())) with check((select private.is_current_user_admin()));
create policy "order_items_admin_delete" on public.order_items for delete to authenticated using((select private.is_current_user_admin()));
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('customer-files','customer-files',false,20971520,array['application/pdf','image/jpeg','image/png']) on conflict(id) do nothing;
create policy "customer_files_insert_own_folder" on storage.objects for insert to authenticated with check(bucket_id='customer-files' and(storage.foldername(name))[1]=(select auth.uid())::text);
create policy "customer_files_select_own_or_admin" on storage.objects for select to authenticated using(bucket_id='customer-files' and((storage.foldername(name))[1]=(select auth.uid())::text or(select private.is_current_user_admin())));
create policy "customer_files_delete_own_or_admin" on storage.objects for delete to authenticated using(bucket_id='customer-files' and((storage.foldername(name))[1]=(select auth.uid())::text or(select private.is_current_user_admin())));
create index if not exists quote_requests_user_created_idx on public.quote_requests(user_id,created_at desc);create index if not exists quote_requests_status_created_idx on public.quote_requests(status,created_at desc);create index if not exists orders_user_created_idx on public.orders(user_id,created_at desc);create index if not exists orders_status_created_idx on public.orders(status,created_at desc);create index if not exists order_items_order_idx on public.order_items(order_id);create index if not exists orders_quote_id_idx on public.orders(quote_id);create index if not exists quote_files_quote_id_idx on public.quote_files(quote_id);create index if not exists quote_files_user_id_idx on public.quote_files(user_id);
-- After creating your own Auth account:
-- insert into private.admins(user_id) values('YOUR-AUTH-USER-UUID');

-- Guest quote validation (kept in sync with the product list exposed by quote.html)
create or replace function private.enforce_guest_quote_limits()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.quantity < 1 or new.quantity > 1000000 then raise exception 'Invalid quantity'; end if;
  if char_length(new.full_name) > 120
     or char_length(new.email) > 254
     or char_length(coalesce(new.phone,'')) > 50
     or char_length(coalesce(new.size,'')) > 120
     or char_length(coalesce(new.paper,'')) > 120
     or char_length(coalesce(new.finish,'')) > 120
     or char_length(coalesce(new.notes,'')) > 5000 then
    raise exception 'Quote field is too long';
  end if;
  if new.email !~* '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' then raise exception 'Invalid email address'; end if;
  if new.product not in ('flyer','brochure','card','apparel','mug','poster','stickers','banner','vinyl','window_graphics','one_way_vision','frosted_film','signage','stationery','design','website') then
    raise exception 'Invalid product';
  end if;
  if (select auth.role())='anon' then
    if (select count(*) from public.quote_requests q where lower(q.email)=lower(new.email) and q.created_at > now()-interval '1 hour') >= 5 then
      raise exception 'Too many quote requests. Please try again later.';
    end if;
  end if;
  return new;
end;
$$;
drop trigger if exists quote_requests_guest_limit_trg on public.quote_requests;
create trigger quote_requests_guest_limit_trg before insert on public.quote_requests for each row execute function private.enforce_guest_quote_limits();
