-- Invoice system for Barlas Print Studio
create sequence if not exists private.invoice_number_seq;

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  order_id uuid not null unique references public.orders(id) on delete restrict,
  order_number text not null,
  user_id uuid not null,
  customer_name text not null,
  customer_email text not null,
  status text not null default 'draft'
    check (status in ('draft','sent','paid','overdue','void')),
  issue_date date not null default current_date,
  due_date date,
  subtotal numeric not null default 0 check (subtotal >= 0),
  gst numeric not null default 0 check (gst >= 0),
  total numeric not null default 0 check (total >= 0),
  notes text,
  sent_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  product text not null,
  description text,
  quantity integer not null check (quantity > 0),
  unit_price numeric not null default 0 check (unit_price >= 0),
  line_total numeric not null default 0 check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists invoices_user_created_idx on public.invoices(user_id,created_at desc);
create index if not exists invoice_items_invoice_idx on public.invoice_items(invoice_id);

alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;

drop policy if exists invoices_select_owner_or_admin on public.invoices;
create policy invoices_select_owner_or_admin on public.invoices
for select to authenticated
using (user_id=(select auth.uid()) or (select private.is_current_user_admin()));

drop policy if exists invoices_admin_insert on public.invoices;
create policy invoices_admin_insert on public.invoices
for insert to authenticated
with check ((select private.is_current_user_admin()));

drop policy if exists invoices_admin_update on public.invoices;
create policy invoices_admin_update on public.invoices
for update to authenticated
using ((select private.is_current_user_admin()))
with check ((select private.is_current_user_admin()));

drop policy if exists invoices_admin_delete on public.invoices;
create policy invoices_admin_delete on public.invoices
for delete to authenticated
using ((select private.is_current_user_admin()));

drop policy if exists invoice_items_select_owner_or_admin on public.invoice_items;
create policy invoice_items_select_owner_or_admin on public.invoice_items
for select to authenticated
using (
  exists (
    select 1 from public.invoices i
    where i.id=invoice_items.invoice_id
      and (i.user_id=(select auth.uid()) or (select private.is_current_user_admin()))
  )
);

drop policy if exists invoice_items_admin_insert on public.invoice_items;
create policy invoice_items_admin_insert on public.invoice_items
for insert to authenticated
with check ((select private.is_current_user_admin()));

drop policy if exists invoice_items_admin_update on public.invoice_items;
create policy invoice_items_admin_update on public.invoice_items
for update to authenticated
using ((select private.is_current_user_admin()))
with check ((select private.is_current_user_admin()));

drop policy if exists invoice_items_admin_delete on public.invoice_items;
create policy invoice_items_admin_delete on public.invoice_items
for delete to authenticated
using ((select private.is_current_user_admin()));

create or replace function private.set_invoice_number()
returns trigger
language plpgsql
security definer
set search_path=''
as $$
begin
  if coalesce(new.invoice_number,'')='' then
    new.invoice_number :=
      'BPS-INV-' || to_char(current_date,'YYYY') || '-' ||
      lpad(nextval('private.invoice_number_seq')::text,4,'0');
  end if;
  return new;
end;
$$;

drop trigger if exists before_invoice_number on public.invoices;
create trigger before_invoice_number
before insert on public.invoices
for each row execute function private.set_invoice_number();

create or replace function private.create_invoice_from_order_impl(
  p_order_id uuid,
  p_due_date date default null,
  p_notes text default null
)
returns table(invoice_id uuid, invoice_number text)
language plpgsql
security definer
set search_path=''
as $$
declare
  v_order public.orders%rowtype;
  v_invoice public.invoices%rowtype;
  v_name text;
  v_email text;
begin
  if not private.is_current_user_admin() then
    raise exception 'Administrator access required';
  end if;

  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'Order not found'; end if;

  select * into v_invoice from public.invoices where order_id=p_order_id limit 1;
  if found then
    return query select v_invoice.id,v_invoice.invoice_number;
    return;
  end if;

  select
    coalesce(nullif(q.full_name,''),nullif(p.full_name,''),nullif(u.raw_user_meta_data->>'full_name',''),u.email,'Customer'),
    coalesce(nullif(q.email,''),u.email)
  into v_name,v_email
  from auth.users u
  left join public.profiles p on p.id=u.id
  left join public.quote_requests q on q.id=v_order.quote_id
  where u.id=v_order.user_id;

  if v_email is null then raise exception 'Customer email not available'; end if;

  insert into public.invoices(
    invoice_number,order_id,order_number,user_id,customer_name,customer_email,
    status,issue_date,due_date,subtotal,gst,total,notes
  )
  values(
    '',v_order.id,v_order.order_number,v_order.user_id,v_name,v_email,
    'draft',current_date,p_due_date,
    greatest(coalesce(v_order.subtotal,0),0),
    greatest(coalesce(v_order.gst,0),0),
    greatest(coalesce(v_order.total,0),0),
    nullif(trim(p_notes),'')
  )
  returning * into v_invoice;

  insert into public.invoice_items(invoice_id,product,description,quantity,unit_price,line_total)
  select v_invoice.id,oi.product,oi.description,oi.quantity,oi.unit_price,oi.line_total
  from public.order_items oi
  where oi.order_id=v_order.id;

  return query select v_invoice.id,v_invoice.invoice_number;
end;
$$;

revoke all on function private.create_invoice_from_order_impl(uuid,date,text) from public;
grant usage on schema private to authenticated;
grant execute on function private.create_invoice_from_order_impl(uuid,date,text) to authenticated;

create or replace function public.create_invoice_from_order(
  p_order_id uuid,
  p_due_date date default null,
  p_notes text default null
)
returns table(invoice_id uuid,invoice_number text)
language sql
security invoker
set search_path=''
as $$
  select * from private.create_invoice_from_order_impl(p_order_id,p_due_date,p_notes);
$$;

revoke all on function public.create_invoice_from_order(uuid,date,text) from public;
grant execute on function public.create_invoice_from_order(uuid,date,text) to authenticated;
